### ISSUE TITLE
Displayed values not aligned with underlying color representation of the phases

### ISSUE THREAD

**Issue by flo269** [mentalilll/ha-vpd-chart#10] opened 2024-07-28 11:17 UTC
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
I'm using a leaf sensor and even though the values displayed are correct, it seems the underlying phase colors are skewed. They seem correct for the tool tip, but not for the actual current values.

**Version of the card**
Version: 1.3.5

**To Reproduce**
This is the configuration I used:
```
type: custom:ha-vpd-chart
min_temperature: 10
max_temperature: 35
min_humidity: 20
max_humidity: 100
min_height: 400
is_bar_view: false
enable_tooltip: true
enable_axes: true
enable_ghostmap: true
enable_triangle: true
enable_crosshair: true
sensors:
  - temperature: sensor.average_temperature
    humidity: sensor.average_humidity
    leaf_temperature: sensor.grow_sensors_leaf_temp_mlx
    name: ''
vpd_phases:
  - upper: 0
    className: gray-danger-zone
    color: null
  - lower: 0
    upper: 0.4
    className: under-transpiration
    color: null
  - lower: 0.4
    upper: 0.8
    className: early-veg
  - lower: 0.8
    upper: 1.2
    className: late-veg
  - lower: 1.2
    upper: 1.6
    className: mid-late-flower
  - lower: 1.6
    className: danger-zone
```

**Screenshots**
Here a screenshot comparing to [vpdchart-card](https://github.com/vpdchart/vpdchart-card)
![Screenshot](https://github.com/user-attachments/assets/845cb6a7-ea44-4ba7-8e13-2af8b7abe893)

**Expected behavior**
The values calculated and displayed to be consistent with the underlying phase colors

**Desktop:**
- Browser [firefox and safari]
- Version [128.0.3 and 17.5 (19618.2.12.11.6)]

**Smartphone:**
- Device: [iPhoneSE 3rd. gen]
- OS: [iOS17.5.1]
- Browser [Latest Home Assistant App]

**Comment by flo269** [comment] 2024-07-28 12:04
I just realized that this is most likely a dup of issue #9. Feel free to close here if the info doesn't help.

**Comment by mentalilll** [comment] 2024-07-28 18:44
Fixed with last commit :)

**Comment by flo269** [comment] 2024-07-28 21:55
Thanks a lot for the new release @mentalilll  - I love the zoom already! :-)

But my problem seems to persist. I updated, cleared browser cache and rebooted the pi. But this is what is I see:
![2](https://github.com/user-attachments/assets/6d8fc29a-6323-4f3b-91f3-e01f18b66852)

**Comment by mentalilll** [comment] 2024-07-28 21:59
ah i see whats happening. the issue is with leaf_temperature_sensor set.

if you remove it, the vpd tooltip is shown on right position. i fix it soon

**Comment by flo269** [comment] 2024-07-28 22:00
Awesome, that's great news. Looking forward to it! Thanks

**Comment by mentalilll** [comment] 2024-07-29 20:18
hope it works now for you :)

**Comment by flo269** [comment] 2024-07-29 20:28
Just installed it - looking great!

Thank you :-)

**Comment by mentalilll** [comment] 2024-07-30 19:19
Hey, should be fixed now :).

**Comment by flo269** [comment] 2024-07-31 10:46
Hey, looking great and we're almost there! :-)

Somehow the wrong RH is displayed, but the VPD is calculated and displayed correctly.

![Kapture 2024-07-31 at 12 43 53](https://github.com/user-attachments/assets/5ffd0d35-b11c-4696-87ee-cad8f1db2432)

**Comment by mentalilll** [comment] 2024-07-31 13:15
should also be fixed now :)

**Comment by flo269** [comment] 2024-08-01 19:28
> should also be fixed now :)

You fixed the bug even before I posted my bug report. Thanks!! ;-)

**Comment by flo269** [comment] 2024-08-01 19:31
But for me it now seems the RH value is not displayed correctly. The VPD is calculated correctly though. Both cards have the same sensors in their config - the ones displayed below. Look at how everything changes immediately upon update, but the wrong RH is displayed.

![Kapture 2024-08-01 at 21 26 04](https://github.com/user-attachments/assets/0876012a-8b4f-40dc-93f4-594bf65fdfce)

**Comment by mentalilll** [comment] 2024-08-01 21:23
thats because that humidity is a theoretical value. calculated from Temperature and kPa. 

the main problem is that you can use more than 1 sensor on my chart. so i can not scale the background like vpdchart does. 
so i maybe can give a option like -> use humidity from sensor (results to wrong position) or use calculated humidity (results to theoretical humidity)

dont know what would be best way to fix that

**Comment by flo269** [comment] 2024-08-01 21:28
If I understand you correctly, maybe you can add an if statement checking if only one sensor is used and then display the real value measured. And if more than one, then do what you're doing now?

**Comment by mentalilll** [comment] 2024-08-05 16:44
yes, right now the chart is correctly, only the RH is "calculated" and not the real value from sensor. maybe a switch for each sensor would make sense

**Comment by flo269** [comment] 2024-08-05 21:37
This also leads to the case, that the ghost map doesn't seem to display things correctly with a leaf sensor? The ghost values displayed on the card seem to be showing the "real" humidity levels, not the calculated ones? I'm not sure whats going here or if I'm just misunderstanding something... :-) Any how: Thanks for all your work!!

![Screenshot 2024-08-05 at 23 36 25](https://github.com/user-attachments/assets/43f1d04d-c4f7-492f-9c8e-75a50de04794)

**Comment by mentalilll** [comment] 2024-08-07 08:48
should be fixed with new release :)

**Closed** 2024-08-07 15:16 UTC
Labels: bug
